---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
spec:
  rules:
  - host: node-app.local
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name  }}
          servicePort: 80
